### ISSUE TITLE
Error Code=500

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.tr-064-community#4]
_From @Charlyphyro on January 28, 2017 12:12_

Hallo soef,
Hab ein error im log mit der version 0.1.31. Was nun anders ist, ich hab das Update meiner fritzbox 7490 auf 06.80 geupdatet. Seit dem kommt diese Fehlermeldung im IoB
error	code=500 sendSOAPActionRequest Error action=GetInfo serviceType=urn:dslforum-org:service:WLANConfiguration:1: 500

Hoffe das hilft dir einwenig. 
Viele Grüße Charly 

_Copied from original issue: soef/ioBroker.tr-064#19_

**Comment by jogibear9988** [comment]
_From @Charlyphyro on February 6, 2017 15:19_

Hallo, Leider noch keine Besserung mit den updates.
+ neuer Fehlermeldungen.
error	code=unknown error code Device responded with fault Error: Credentials incorrect
forEachHostEntry: in getGenericHostEntry 32:Error: sendSOAPActionRequest Error action=GetGenericHostEntry serviceType=urn:dslforum-org:service:Hosts:1: - {'code':''}


Mit freundlichen Grüßen
Charly

**Comment by jogibear9988** [comment]
_From @MeisterTR on April 12, 2018 4:40_

den Fehler kann ich bestätigen ich habe eine 6490 (Kabel)  Fehler:

host.smarthome | 2018-04-12 06:32:17.948 | error | instance system.adapter.tr-064.0 terminated with code 1 ()
-- | -- | -- | --
tr-064.0 | 2018-04-12 06:32:12.933 | error | ~
tr-064.0 | 2018-04-12 06:32:12.933 | error | ~~ If configuration, networt, IP address, etc. ok, try to restart your FritzBox
tr-064.0 | 2018-04-12 06:32:12.933 | error | ~~ Fatal error. Can not connect to your FritzBox.
tr-064.0 | 2018-04-12 06:32:12.933 | error | ~
tr-064.0 | 2018-04-12 06:32:12.932 | error | Error: sendSOAPActionRequest Error action=GetInfo serviceType=urn:dslforum-org:service:WLANConfiguration:1: 500 - {"code":500}

Anmeldedaten sind alle korrekt node 8 Alles auf dem neusten stand

**Comment by jogibear9988** [comment]
_From @Marty56 on July 26, 2018 3:22_

Ähnliches Bild hier. 
Fehler wird bei mir ausgelöst, wenn das Handy das Wlans  nicht mehr erreichen kann.
Wenn das Handy sich dann wieder im Wlan eingeloggt ist, dann verschwindet der Fehler.
Es scheint auch davon abzuhängen, ob das Handy sich ins Gäste Wlan einloggt hatte oder nicht.

**Comment by thunder1504** [comment]
Hi zusammen, ich habe leider das selbe Problem:
host.raspberrypi | 2019-05-16 17:34:54.378 | error | instance system.adapter.tr-064.0 terminated with code 1 ()
-- | -- | -- | --
tr-064.0 | 2019-05-16 17:34:49.330 | error | ~
tr-064.0 | 2019-05-16 17:34:49.330 | error | ~~ If configuration, networt, IP address, etc. ok, try to restart your FritzBox
tr-064.0 | 2019-05-16 17:34:49.329 | error | ~~ Fatal error. Can not connect to your FritzBox.
tr-064.0 | 2019-05-16 17:34:49.329 | error | ~
tr-064.0 | 2019-05-16 17:34:49.324 | error | Error: Device responded with fault Error: Credentials incorrect - {}
tr-064.0 | 2019-05-16 17:34:46.425 | info | starting. Version 0.4.18 in /opt/iobroker/node_modules/iobroker.tr-064, node: v10.15.3
host.raspberrypi | 2019-05-16 17:34:42.781 | info | instance system.adapter.tr-064.0 started with pid 15802
host.raspberrypi | 2019-05-16 17:34:12.764 | info | Restart adapter system.adapter.tr-064.0 because enabled
host.raspberrypi | 2019-05-16 17:34:12.763 | error | instance system.adapter.tr-064.0 terminated with code 1 ()
tr-064.0 | 2019-05-16 17:34:07.726 | error | ~
tr-064.0 | 2019-05-16 17:34:07.726 | error | ~~ If configuration, networt, IP address, etc. ok, try to restart your FritzBox
tr-064.0 | 2019-05-16 17:34:07.725 | error | ~~ Fatal error. Can not connect to your FritzBox.
tr-064.0 | 2019-05-16 17:34:07.725 | error | ~
tr-064.0 | 2019-05-16 17:34:07.720 | error | Error: sendSOAPActionRequest Error action=GetInfo serviceType=urn:dslforum-org:service:WLANConfiguration:1: 500 - {"code":500}
